### ISSUE TITLE
Easier Parallelisation of Requests

### ISSUE THREAD

**Issue by garthenweb** [garthenweb/pexo#2]
With d12c52ddc2533b7b9539ff0b217db60ce177aa0f a base implementation for requests was introduced which handles asynchronous tasks and will bundle requests done at the same time together to safe resources.

In some situations requests depend on each other so they will create a waterfall. This is hard to get around.

But if requests are independent, they can run in parallel.

This is a naive implementation to fetch products on a category to filter them by the liked products of the user:

``` javascript
const requestFavoriteProducts = async (location, userToken) => {
  const category = await request(getCategoryByPathName(location.pathname));
  const products = await request(getProductsByCategoryId(category.id));
  const favoriteProductIds = await request(
    getFavoriteProductIdsByUserToken(userToken)
  );

  return products.filter((product) => favoriteProductIds.includes(product.id));
};
```

It fetches all requests after each other. So the request for the favorite product ids will be the last, even though it could have fetched in parallel with the category.

So you might want to rewrite this as following to improve performance:

``` javascript
const requestFavoriteProducts = async (location, userToken) => {
  const [products, favoriteProductIds] = await Promise.all([
    request(getCategoryByPathName(location.pathname)).then((category) => {
      return request(getProductsByCategoryId(category.id));
    }),
    request(getFavoriteProductIdsByUserToken(userToken)),
  ]);

  return products.filter((product) => favoriteProductIds.includes(product.id));
};
```

This will now run categories/ products and favorite products in parallel which speeds up the whole execution as we can make use of idle times.

But it is harder to read, understand and debug. Maybe for this simple example, it is still okay but it might become harder for more complex cases. Also, you need to be aware of the waterfall you created in the first place which is a mental overhead during development.

A proposal for a solution is the following:

``` javascript 
const requestFavoriteProducts = async (location, userToken) => {
  const category = request(getCategoryByPathName(location.pathname));
  const products = request(getProductsByCategoryId(category.id));
  const favoriteProductIds = request(
    getFavoriteProductIdsByUserToken(userToken)
  );

  return Promise.all(
    products.map(async (product) =>
      (await favoriteProductIds).includes(await product.id)
    )
  );
};
```

The main difference compared to the first example is that we skip all kinds of awaits while fetching the data and first await especially when we want to normalize/ transform the data into a view state.

This allows writing the code however you like and the framework will handle the rest for you.

This could even work nicely in combination with generator functions to push an early state before all requests resolved. Assume we also like to show a headline based on the category name. As soon as the category is loaded we could yield it to the view without increasing the complexity of the code or delaying other requests.

``` javascript
async function* requestFavoriteProducts(location, userToken) {
  const category = request(getCategoryByPathName(location.pathname));
  const products = request(getProductsByCategoryId(category.id));
  const favoriteProductIds = request(
    getFavoriteProductIdsByUserToken(userToken)
  );

  yield {
    headline: await category.name,
    products: [],
  };

  return {
    headline: await category.name,
    products: await Promise.all(
      products.map(async (product) =>
        (await favoriteProductIds).includes(await product.id)
      )
    ),
  };
}
```

This would not be possible with the first approach at all.

**How could this work?**

Instead of just returning a promise from a request, we wrap it into a `Proxy`.

Whenever a getter is called it, instead of a sync value, returns a promise which waits as long as the async task takes.

As soon as the task resolves, it also resolves the promise for the getter as well but just returns the value for the key that was requested.

If the key does not exist it will just throw as usual. If it exists, the value is returned.

As we pass promises to other requests resources now, we need to ensure that the requested resource is async by default and waits for its request to be done as long as the former request takes.

We basically move the awaiting part into the next request instead of letting it handle by the developer.

Possible Caveat:

* Proxies are not supported in IE and there is no way to polyfill it. But we could allow the developer to insert a schema for each request by hand so based on the expected structure, the promise structure can be generated up front. This is also something that could be handled statically at compile time in case we have information on the request structure (e.g. in case GraphQL is used which already exposes a schema, or maybe even using typescript interfaces).

**Comment by Kadrian** [comment]
I think these are some cool ideas. Reminds me a little bit of `redux-saga` as an alternative way to manage async control flow: https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/sagas/index.js

But in your last example, as much as you might not need to "worry" anymore at the top about what can be parallelized, the more you'll worry at the bottom where to place all the `await`s. Because you still *do* need to remember to place them before `favoriteProductIds ` and before `product.id` and these places don't naturally "afford" awaits in 99% of the code a developer is used to write. So your last example would require quite some re-thinking / re-learning.

The root issue here, the "creating-a-waterfall-mistake" you're trying to find a solution for, in my opinion often stems from the fact that in e.g. between await 2 and await 3 there are ~50 unrelated lines of code so as a developer, you're not clearly seeing the async actions in sequence and you forget to parallelize. 

I believe the control flow in your second example becomes easy to understand by extracting some functions and using `async / await` instead of `.then`.

```javascript
// Piece of logic 1
const getAllProducts = async (location) => {
  const category = await request(getCategoryByPathName(location.pathname));
  
  return request(getProductsByCategoryId(category.id));
}

// Piece of logic 2
const getFavoriteProductIds = () => {
  return request(getFavoriteProductIdsByUserToken(userToken))
}

const requestFavoriteProducts = async (location, userToken) => {
  const [products, favoriteProductIds] = await Promise.all([
    getAllProducts(location),
    getFavoriteProductIds()
  ]);

  return products.filter((product) => favoriteProductIds.includes(product.id));
};
```

With extracted pieces of logic, even the "complex cases" you mention should become understandable.

I think it only gets trickier when these pieces of logic start growing and we have different case:
Piece of logic 2 depends on piece of logic 1, but both could still *start* and do some requests already.

So here would be a (little artificial) example where this could become a problem:

```javascript
const getAllProducts = async (location) => {
  const category = await request(getCategoryByPathName(location.pathname));
  
  return request(getProductsByCategoryId(category.id));
}

const getAllOutfitsByProducts = async (products, userToken) => {
  // THIS REQUEST SEEMS TO BE RELATED TO OUTFITS, BUT DOESN'T DEPEND ON `products`
  // Solution: Move it outside of this piece of logic. But might be missed.
  const countrySpecificOutfitCategories = await request(getOutfitCategoriesForMyCountry(userToken));

  const productIds = products.map(product => product.id)

  return request(getOutfitsByProductsAndCategories(productIds, countrySpecificOutfitCategories));
}

const requestProductsWithOutits = async (location, userToken) => {
  const products = await getAllProducts(location);
  const outfits = await getAllOutfitsByProducts(products, userToken);

  return products.map((product) => ({ ...product, outfits: outfits }));
};
``` 

But I wouldn't know how to prevent this issue or how to solve this in an easier-to-understand way using generators. Maybe you've got an idea?

**Comment by garthenweb** [comment]
Thanks for the feedback :)

> I think these are some cool ideas. Reminds me a little bit of redux-saga as an alternative way to manage async control flow: https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/sagas/index.js

Nor 100% sure what those concepts actually share beside of my last example where generators are used to push the first state early. Would you like to extend on that?

For me, the saga example looks super confusing, not even sure what is going on there. I think they also try to solve a different problem, as they also have login actions in there where this proposal is only about loading data, not mutating it.

> But in your last example, as much as you might not need to "worry" anymore at the top about what can be parallelized, the more you'll worry at the bottom where to place all the awaits. Because you still do need to remember to place them before favoriteProductIds and before product.id and these places don't naturally "afford" awaits in 99% of the code a developer is used to write. So your last example would require quite some re-thinking / re-learning.

I would not compare against the last example as this is nothing that can be achieved with the other approach, it is just a goodie on top. But your arguments are valid for my example without generator functions as well.

I thought about that as well. I would like to evaluate if we could iterate over the returned data structure so that we can just return a random promise structure. This will for sure not work for all edge cases, but I believe with some nice utility functions this could become easier as well.

First of all, I would like to mention that this will not be the silver bullet to solve all your issues. And you can still go on without the nested promises if you like or it makes sense for your code. But if offers some additions that don't require to think too much about parallelism.

> The root issue here, the "creating-a-waterfall-mistake" you're trying to find a solution for, in my opinion often stems from the fact that in e.g. between await 2 and await 3 there are ~50 unrelated lines of code so as a developer, you're not clearly seeing the async actions in sequence and you forget to parallelize.

I agree. Anyhow, from my experience, there are a lot of cases where there is a reason why those 50 lines are inserted between those cases. Most probably because they have one dependency for a specific request/ data. With the proposed approach you can kind of safely, without thinking about request order, define all your network calls at the top, and use them in another block of code, maybe even in another function. I think this can become a huge benefit.

> I believe the control flow in your second example becomes easy to understand by extracting some functions and using async / await instead of .then.

Fair point. I think this should always be a considerable option.
Still, it can make the code harder to understand. Compare your example against mine. You need to jump a lot to understand the whole data flow and all details. With more extracted calls and details, this can become super hard to read, as you might jump into a lot of different files. From my experience, this can become a huge overhead when trying to understand what is going on.

Also, you still need to detect on your own that `getFavoriteProductIds` and the `getAllProducts`.

But there is no black and white, it depends on your situation!



> But I wouldn't know how to prevent this issue or how to solve this in an easier-to-understand way using generators. Maybe you've got an idea?

With the proposed apis, this could be written as:
``` javascript
const requestProductsWithOutits = async (location, userToken) => {
  const category = request(getCategoryByPathName(location.pathname));
  const products = request(getProductsByCategoryId(category.id));
  const countrySpecificOutfitCategories = request(
    getOutfitCategoriesForMyCountry(userToken)
  );
  const outfits = request(
    getOutfitsByProductsAndCategories(
      products.then(mapId),
      countrySpecificOutfitCategories
    )
  );
  const syncOutfits = await outfits;
  const syncProducts = await products;
  return syncProducts.map((product) => ({ ...product, outfits: syncOutfits }));
};

const mapId = (list) => list.map(({ id }) => id);
```

And if you like, as it might be more readable, just combine both concepts:

``` javascript
const getAllProducts = (location) => {
  const category = request(getCategoryByPathName(location.pathname));
  return request(getProductsByCategoryId(category.id));
}

const getAllOutfitsByProducts = (products, userToken) => {
  const countrySpecificOutfitCategories = request(getOutfitCategoriesForMyCountry(userToken));

  const productIds = products.then(mapId)

  return request(getOutfitsByProductsAndCategories(productIds, countrySpecificOutfitCategories));
}

const requestProductsWithOutits = async (location, userToken) => {
  const products = getAllProducts(location);
  const outfits = getAllOutfitsByProducts(products, userToken);

  const syncOutfits = await outfits;
  const syncProducts = await products;
  return syncProducts.map((product) => ({ ...product, outfits: syncOutfits }));
};


const mapId = (list) => list.map(({ id }) => id);
```

This solves the performance issue by more or less removing `await` statements.

I don't think generator functions are the best tool for improving parallelism on this level, as they would stop the code execution instead of parallelizing it.

But they are a great tool to push early updates to the view component. See the following example: https://github.com/garthenweb/pexo/blob/master/example/chunks/chunk2.tsx#L29
